### ISSUE TITLE
Describe schema

### ISSUE THREAD

**Issue by lffsantos** [Pypular/pypular#18]
Create file in project something like doc/shema.md or in wiki, explaining the schema.

**Comment by fabiocerqueira** [comment]
What exactly is a schema.md? Could you show some example?

**Comment by lffsantos** [comment]
It can have another name .. it doesn't matter...
Is more to explain the relationship between.
Tweet - Url - Hashtag
Sometimes it gets a bit confusing
The 'hashtag' for example should be the 'tweet' instead of 'URL' no?

**Comment by fabiocerqueira** [comment]
```
+-------+                   +--- ---+                       +--------+
|       |     +--------+    |       |    +------------+     |        |
| Tweet +-----+TweetURL+----+  URL  +-----|HashtagURL|------+ Hastag |
|       |     +--------+    |       |    +------------+     |        |
+-------+                   +-------+                       +--------+
```

**Comment by denisra** [comment]
The goal was to determine what were the most "popular"/most tweeted urls, so the URL is our main entity.
We can do that by counting how many tweets referenced a given url through the tweet-url relationship.
Then we have a relationship between hashtags and the urls. That way, we can show urls that are associated with certain hashtags.

Does that make sense?

@fabiocerqueira diagram above shows what I just tried to describe above.
